# Generated by Django 5.2.4 on 2025-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_options_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("expense", "Expense")], max_length=10
            ),
        ),
    ]
